### ISSUE TITLE
Android plugin after install scripts references incorrect GIT repo

### ISSUE THREAD

**Issue by stefangordon** [AllJoyn-Cordova/cordova-plugin-alljoyn#2]
Noticed the Android script pulls a seperate copy of AJTCL down from what the other platforms use.  Presumably just due to development needs, but this issue is to remind us to resolve that and pull a single copy down.

**Comment by vjrantal** [comment]
Nowadays, all platforms use ajtcl from https://github.com/AllJoyn-Cordova/ajtcl.git.
