### ISSUE TITLE
Plugin does not compile for windows, AJ_Introspect.c

### ISSUE THREAD

**Issue by stefangordon** [AllJoyn-Cordova/cordova-plugin-alljoyn#3]
AJ_Introspect fails to compile.

`Conversion from 'void*' to pointer to non-'void' requires an explicit cast`

``` c
AJ_InterfaceDescription* AJ_InterfacesCreate()
{
    char ***array;
    array = AJ_Malloc(sizeof(char**));
    array[0] = NULL;
    return (AJ_InterfaceDescription *) array;
}
```

This method doesn't appear to have been changed at all by Ivan's commit, so perhaps it never worked?  Any ideas?

**Comment by stefangordon** [comment]
Saw this during both cordova build windows and from inside VS.  Have not confirmed on other platforms.

**Comment by stefangordon** [comment]
Update from conversations:
This is new functionality which hasn't made it to the mainline AJTCL yet but is important.  We should try to fix the errors in AJ_Introspect so it compiles across all platforms.

**Comment by vjrantal** [comment]
This issue was fixed by a commit to the ajtcl repo https://github.com/AllJoyn-Cordova/ajtcl/commit/2157d1cf17a5ec83761b09ded183f44baab91e33 .
