### ISSUE TITLE
When Cordova issue 8123 is resolved, update instructions

### ISSUE THREAD

**Issue by stefangordon** [AllJoyn-Cordova/cordova-plugin-alljoyn#4]
This is just a reminder to monitor this bug, which appears to be progressing very quickly:
https://issues.apache.org/jira/browse/CB-8123

When resolved we should update all appropriate documentation.

**Comment by vjrantal** [comment]
I did https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn/pull/22 and https://github.com/AllJoyn-Cordova/cordova-chat-alljoyn/commit/786c63a90aa832fd8c8dd8541a57b93f5ae75745 based on the fact that the latest Cordova release contains the features we need.
