### ISSUE TITLE
iOS: Crash After Re-Connect

### ISSUE THREAD

**Issue by garethsony** [AllJoyn-Cordova/cordova-plugin-alljoyn#40]
Attempting to connect after a connection failure results in a crash. 
To reproduce:
1.) Call AllJoyn.connect with a guaranteed failure condition (e.g. turn WiFi off).
2.) Observe the on-failure callback is called.
3.) Issue a second call to AllJoyn.connect (this will result in a crash).

**Comment by garethsony** [comment]
I created a pull request for this issue: https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn/pull/41.

**Comment by obsoleted** [comment]
I believe this is closed as #41 has been merged in.
