### ISSUE TITLE
[Windows] Can't connect to a Windows10 AllJoyn Router Service

### ISSUE THREAD

**Issue by sgrebnov** [AllJoyn-Cordova/cordova-plugin-alljoyn#57]
I use built-in `AllJoyn Router Service` on Windows 10 and [cordova-lighting-alljoyn](https://github.com/AllJoyn-Cordova/cordova-lighting-alljoyn) sample for testing.

Android implementation works fine and sample app can find and connect to the router.

When using Windows Cordova platform the following line always reports connection timeout. I tried to increase timeout, restart service, Windows 8.1 and Windows UAP projects (Desktop/x64, sample app is run on the same PC w/ Ajn Service).

```
var status = AllJoynWinRTComponent.AllJoyn.aj_FindBusAndConnect(busAttachment, daemonName, 5000);
```

PS. Awesome work

**Comment by vjrantal** [comment]
Could this relate to the loopback restrictions with UAP/UWP apps? You could try with something like http://loopback.codeplex.com/ to see if your app should be able to talk to local services.

Another alternative might be firewall so trying out to temporarily disable the firewall might be one way to try out if that is causing the issue.

I have to admit I have sometimes seen similar problems myself and sometimes run a router externally from the Windows machine as a workaround. Naturally, this shouldn't be necessary, but the in-built Windows 10 router should be able to serve also local apps.

**Comment by sgrebnov** [comment]
I've reviewed `loopback exemption` and it is enabled. I also have some other Alljoyn apps generated using `Visual Studio Alljoyn Extension` and they work fine on the same PC. I'm looking on the AllJoyn trace and the only strange  thing I see is the following errors, but I'm not sure how critical they are

https://gist.github.com/sgrebnov/25fb9f31c186dd512085 

```
Error: LoadNVFromFile() failed
Error: StoreNVToFile() failed
Error: StoreNVToFile() failed
```

PS. I've also tenabled Alljoyn ETW Log Output (https://channel9.msdn.com/Blogs/Internet-of-Things-Blog/Troubleshooting-AllJoyn-with-Windows-10-Insider-Preview-Builds) but don't see new records during plugin work

PPS. AllJoyn capability is enabled when testing as UAP

**Comment by vjrantal** [comment]
Did you try to stab the firewall?

I think [this discussion](https://lists.allseenalliance.org/pipermail/allseen-core/2015-October/002562.html) might be also worth checking out even though there, I believe the scenario was a little bit different to what you are having.

**Comment by sgrebnov** [comment]
Thank you for your help, @vjrantal. Unfortunately disabling firewall didn't help. I'm closing this issue as I don't think there is anything related to plugin implementation... I'll try to investigate this if I have a chance - will post results here if I find problem cause (but it is low priority now)

**Comment by vjrantal** [comment]
One more thing came to my mind.

I am not sure if the router checks the AllJoyn capability from the app that tries to connect to it, but you could try manually adding https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/AllJoyn/ConsumerExperiences/cs/Package.appxmanifest#L52 into your manifest and see if that makes a difference.

**Comment by sgrebnov** [comment]
Tried this, didn't help, thank you anyway :)

**Comment by sgrebnov** [comment]
I was able to connect by setting  `AJ_CONNECT_LOCALHOST` flag. I think I can use the following connect spec `tcp:addr=127.0.0.1,port=9955`, but looks like there is no currently way to specify it when using the plugin.

**Comment by vjrantal** [comment]
Thanks for the information.

The flag seems to be documented like:

```
#define AJ_CONNECT_LOCALHOST        0           //Enable to bypass discovery and connect locally
```

It sounds like it bypass the discovery entirely so probably not very often, the plugin user would want to build ajtcl using that flag or even set the mentioned connect spec. What do you think?

However, this indicates that the issue is in the discovery of the router rather than connecting to it.

**Comment by sgrebnov** [comment]
I tend to agree, you may want to just document this. But having a way to specify connection spec may be still useful in some cases - I think this could be achieved via config.xml plus hooks or optional parameter to connect method.

PS. I don't know if thin client supports special configuration files, but it could be another good alternative.
